# AdvancedCaptcha Configuration
# This file controls the behavior of the AdvancedCaptcha plugin.
# All settings are organized into sections for clarity.

# General settings for the plugin
general:
  # Default language for messages (e.g., 'en', 'ru', 'ua')
  default-language: en
  # Supported languages for player locale detection
  supported-languages:
    - en
    - ru
    - ua
  # Logging level (INFO, DEBUG, WARN)
  log-level: INFO

# Captcha settings
captcha:
  # Type of captcha to use (BUTTON, MATH, RANDOM)
  type: RANDOM
  # Cooldown for re-verification in milliseconds (default: 6 hours = 21600000 ms)
  cooldown: 21600000
  # Minimum number of buttons in captcha (min: 2)
  button-count-min: 4
  # Maximum number of buttons in captcha (max: 10)
  button-count-max: 7
  # Maximum number of attempts to pass captcha
  max-attempts: 2
  # Timeout for captcha completion in seconds
  timeout: 300
  # Commands allowed during captcha verification
  allowed-commands:
    - /login
    - /register
  # Colors used for buttons (supported: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE)
  button-colors:
    - BLUE
    - GREEN
    - RED
    - YELLOW
    - WHITE
    - BLACK
    - GRAY
    - LIGHT_PURPLE
  # Sound and particle effects
  success-sound: ENTITY_PLAYER_LEVELUP
  fail-sound: ENTITY_VILLAGER_NO
  success-particle: VILLAGER_HAPPY
  fail-particle: SMOKE_NORMAL
  # Anti-macro threshold in milliseconds (minimum time to click to avoid macro detection)
  anti-macro-threshold: 200
  # Freeze settings to restrict player actions during captcha
  freeze:
    # Enable or disable freezing player actions
    enabled: true
    # Slowness effect level (1-6, higher values make player slower)
    slowness-level: 6

# Settings specific to the mathematical captcha
math-captcha:
  # Allowed mathematical operations (PLUS, MINUS, MULTIPLY)
  allowed-operations:
    - PLUS
    - MINUS
    - MULTIPLY
  # Minimum value for numbers in math expressions
  number-range-min: 1
  # Maximum value for numbers in math expressions
  number-range-max: 20