name: AdvancedCaptcha
version: '${project.version}'
main: feelingalive.advancedcaptcha.AdvancedCaptchaPlugin
api-version: 1.16
authors: [FeelingAlive]
commands:
  captcha_click:
    description: Internal command for captcha click handling
    usage: /<command> <click_value>